TicketStore/TicketStore/Controllers/CategoryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TicketStore.Models.BindingModels.Event;
using TicketStore.Models.EntityModels;
using TicketStore.Models.ViewModels.Category;
using TicketStore.Services;
//using TicketStore.Services.Interfaces;

namespace TicketStore.Controllers
{
    [RoutePrefix("category")]
    public class CategoryController : Controller
    {
        private CategoryService service;

        //public CategoryController()
        //{
        //}

        public CategoryController()
        {
            this.service = new CategoryService();
        }

        [HttpGet]
        [Route("concerts")]
        [AllowAnonymous]
        public ActionResult Concerts()
        {

            IEnumerable<CategoryViewModel> view = this.service.GetAllConcerts();

            return View(view);
        }

        [HttpGet]
        [Route("culture")]
        [AllowAnonymous]
        public ActionResult Culture()
        {
            IEnumerable<CategoryViewModel> view = this.service.GetAllCulture();

            return View(view);
        }

        [HttpGet]
        [Route("sport")]
        [AllowAnonymous]
        public ActionResult Sport()
        {
            IEnumerable<CategoryViewModel> view = this.service.GetAllSports();

            return View(view);
        }

        [HttpGet]
        [Route("otherevents")]
        [AllowAnonymous]
        public ActionResult OtherEvents()
        {
            IEnumerable<CategoryViewModel> view = this.service.GetAllOtherEvents();

            return View(view);
        }

       
    }
}

TicketStore/TicketStore/Controllers/SearchController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TicketStore.Models.EntityModels;
using TicketStore.Models.ViewModels;
using TicketStore.Services;

namespace TicketStore.Controllers
{
    [RoutePrefix("search")]
    public class SearchController : Controller
    {

        private SearchService service;

        //public SearchController()
        //{
            
        //}

        public SearchController()
        {
            this.service = new SearchService();
        }

        [HttpGet]
        [Route("searchform")]
        public ActionResult SearchForm()
        {
            All view = new All()
            {
                Categories = this.service.GetAllCategories(),
                Events = this.service.GetAllEvents().ToList()
            };

            return this.View(view);
        }

        // GET: Search
        [HttpPost]
        [Route("searchcategory")]
        public PartialViewResult SearchCategory(string keyword)
        {
            IEnumerable<Category> category = this.service.SearchCategory(keyword);

            return this.PartialView("_CategorySearch", category);
        }

        [HttpPost]
        [Route("searchevent")]
        public PartialViewResult SearchEvent(string keywordEvent)
        {
            IEnumerable<Event> events = this.service.SearchEvent(keywordEvent);

            return this.PartialView("_EventSearch", events);
        }

        [HttpPost]
        [Route("searchlocation")]
        public PartialViewResult SearchLocation(string keywordLocation)
        {
            IEnumerable<Event> events = this.service.SearchLocation(keywordLocation);

            return this.PartialView("_LocationSearch", events);
        }
    }
}

TicketStore/TicketStore/Views/Shared/Unauthorized.cshtml
@{
    ViewBag.Title = "Unauthorized";
}

<h2>Unauthorized</h2>

TicketStore/TicketStore/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Styles.Render("~/Content/css/Site.css")
    @Styles.Render("~/Content/css/Ticket.css")
    @Styles.Render("~/Content/less")
    @Styles.Render("~/Content/scss")
    @Scripts.Render("~/bundles/modernizr")


</head>

<body>
<style>
     .footer {
         position: fixed;
         bottom: 0;
left: 0;
right: 0;
background-color: #101010
}
</style>
    <div class="navbar navbar-inverse">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("CULTURE & MUSIC", "Index", "Home", new { area = "" }, new { @class = "navbar-brand", @style = "color: blue" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("   ", "", "")</li>

                    @*<li>@Html.ActionLink("HOME", "Index", "Home", new { area = "" }, new { @style = "color: deeppink" })</li>*@



                    @*@using (Html.BeginForm("AllCategories", "Category"))
                        {
                            @Html.DropDownList("Id", new SelectList(ViewBag.AllCategories, "Id", "Name"), new { @class = "form-control", onchange = "$(this.form).submit();" })
                        };*@

                    @*<li class="dropdown">
                             <a class="dropdown-toggle" data-toggle="dropdown" href="#">Събития <span class="caret"></span></a>
                             <ul class="dropdown-menu" role="menu">
                                 <li>@Html.ActionLink("Концерти", "Concerts", "Category")</li>
                                 <li>@Html.ActionLink("Култура", "Culture", "Category")</li>
                                 <li>@Html.ActionLink("Спорт", "Sport", "Category")</li>
                                 <li>@Html.ActionLink("Други", "OtherEvents", "Category")</li>
                             </ul>
                        </li>*@

                    <li>@Html.ActionLink("CONCERTS", "Concerts", "Category", new { area = "" }, new { @style = "color: yellow" })</li>
                    <li>@Html.ActionLink("CULTURE", "Culture", "Category", new { area = "" }, new { @style = "color: deeppink" })</li>
                    <li>@Html.ActionLink("SPORTS", "Sport", "Category", new { area = "" }, new { @style = "color: lawngreen" })</li>
                    <li>@Html.ActionLink("OTHER EVENTS", "OtherEvents", "Category", new { area = "" }, new { @style = "color: aqua" })</li>
                    <li>@Html.ActionLink("SEARCH", "SearchForm", "Search", new { area = "" }, new { @class = "btn btn-danger" , @style="color: black"})</li>

                </ul>

                @*<form class="navbar-form navbar-left">
                        <div class="input-group">
                            <input type="text" class="form-control" placeholder="Search">
                            <div class="input-group-btn">
                                <button class="btn btn-default" type="submit">
                                    <i class="glyphicon glyphicon-search"></i>
                                </button>
                            </div>
                        </div>
                    </form>*@
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>

    @RenderBody()

        <footer class="footer">
            <br />
            <div>
                <div class="row">
                    <div class="col-sm-2">
                        <a href="#"><h4></h4></a>
                    </div>
                    <div class="col-sm-2">
                        <h4>@Html.ActionLink("About Us", "About", "Home", new { area = "" }, new { @style = "color: deeppink" })</h4>
                    </div>
                    <div class="col-sm-2">
                        <a href="#"><h4>@Html.ActionLink("Partners", "Partners", "Home", new {area=""},  new { @style = "color: yellow" })</h4></a>
                    </div>
                    <div class="col-sm-2">
                        <a href="#"><h4>@Html.ActionLink("Contact Us", "Contact", "Home", new { area = "" }, new { @style = "color: blue" })</h4></a>
                    </div>
                    <div class="col-sm-2">
                        <a href="#"><h4>@Html.ActionLink("More Culture & Music", "Concerts", "Category", new { area = "" }, new { @style = "color: lawngreen" })</h4></a>
                    </div>
                </div>
            </div>
        </footer>
        <br />

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>